#¶Ë¿ÚºÅ
server:
  port: 8080

#jdbc
spring:
  datasource:
    url: jdbc:mysql:///db_gm?useSSL=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

#ÅäÖÃÊÓÍ¼½âÎöÆ÷
mvc:
  view:
    prefix: /
    suffix: .html

#mybatis
mybatis:
  type-aliases-package: com.gm.springboot02.pojo
